version: '3.4'
services:
  flowcentral:
    image: axway/flowcentral:1.0
    stdin_open: true
    hostname: "flowcentral"
    tty: true
    expose: [12554, 12553, 8081, 5701]
    environment:
        ### EULA ###
        ACCEPT_EULA: "yes"

        ### General ###
        FQDN                      : "flowcentral"
        HOSTNAME                  : "flowcentral"
        CG_SHARED_SECRET          : "Secret01"
        ENCRYPTION_KEY            : "Secret01"
        GENERAL_LOGGING_LEVEL     : "INFO"

        ### APIC settings ###
        UME_APIC_USE_CATALOG      : "true"       # Enable or disable connection to Api Catalog
        UME_APIC_PUBLICKEY        : "/opt/axway/configs/catalog-public-key.pem"
        UME_APIC_PRIVATEKEY       : "/opt/axway/configs/catalog-private-key.pem"
        UME_APIC_HOST             : "https://apicentral.axway.com"
        UME_APIC_CLIENTID         : "DOSA_XXXXXXXXXXXXXXXXXXXX"           # This must be filled in after you log into api catalog and register the keys
        UME_APIC_TOKENURL         : "https://login.axway.com/auth/realms/Broker/protocol/openid-connect/token"

        ### Mongo ###
        MONGODB_HOST              : "fcmongo"
        MONGODB_PORT              : "27018"
        MONGODB_ROOT_NAME         : "root"
        MONGODB_USER_NAME         : "storage"
        MONGODB_USER_PASSWORD     : "storage"

        ### Flow Central configuration type ###
        IDP_CONFIGURATION         : "internal"  

        ### Buisness ###
        BUSINESS_USE_CUSTOM       : "true"
        BUSINESS_CA_CERTIF_ALIAS  : "business" # Certificate Alias
        BUSINESS_CA_FILE          : "/opt/axway/configs/businessca.p12" # You can use the keys generated by the scripts or generate others, Edit the name of the certs if this is the case
        BUSINESS_CA_PASSWORD      : "Secret01" # Certificate password

        ### Governance ###
        GOVERNANCE_CA_CERTIF_ALIAS: "governance" # Certificate Alias
        GOVERNANCE_CA_FILE        : "/opt/axway/configs/governanceca.p12"  # You can use the keys generated by the scripts or generate others, Edit the name of the certs if this is the case
        GOVERNANCE_CA_PASSWORD    : "Secret01" # Certificate password

        ### Security ###
        SECURITY_CG_UI_ALIAS      : "ui" # Certificate Alias
        SECURITY_CG_UI            : "/opt/axway/configs/uicert.p12" # You can use the keys generated by the scripts or generate others, Edit the name of the certs if this is the case
        SECURITY_CG_UI_PASSWORD   : "Secret01"  # Certificate password

        ### Certificates ### 
        CERTIFICATE_EXPIRATION_NOTIFICATION: "60" 
    ports:
      - 8081:8081
      - 5701:5701
      - 12553:12553
      - 12554:12554
    depends_on:
      - fcmongo
    volumes:
     - "./mounts/fc_logs:/opt/axway/fc_logs"
     - "./mounts/fc_keys:/opt/axway/FlowCentral/data/keys/com.axway.nodes.ume"
     - "./mounts/configs:/opt/axway/configs"
     - "./mounts/configs:/opt/axway/FlowCentral/data/CGLicense"

  fcmongo:
    build: ./mongo-3.4/ 
    expose:
      - 27018
    volumes:
      - "./mounts/mongo_data:/data/db/"
    ports:
      - 27018:27018
    environment:
      MONGODB_ADMIN_USER              : root
      MONGODB_ADMIN_PASS              : storage
      MONGODB_APPLICATION_DATABASE    : umcft
      MONGODB_APPLICATION_USER        : storage
      MONGODB_APPLICATION_PASS        : storage

